fixtures:
  symlinks:
    razor: "#{source_dir}"
  repositories:
    apt:
      repo: 'https://github.com/puppetlabs/puppetlabs-apt.git'
      tag:  '2.1.0'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      tag:  '1.2.3'
    postgresql:
      repo: 'https://github.com/puppetlabs/puppetlabs-postgresql.git'
      tag:  '4.3.0'
    archive:
      repo: 'https://github.com/voxpupuli/puppet-archive.git'
      tag:  'v3.0.0'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      tag:  '4.6.0'
